version: "3"
services:
  web-app:
    container_name: web-app
    hostname: web-app.local
    build: ./web-app
    environment:
      - REACT_APP_PORT="3000"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./web-app/src:/srv/app/web-app/src
      - ./web-app/public:/srv/app/web-app/public
    links:
      - command-line
    command:
      npm run start
  command-line:
    container_name: command-line
    hostname: command-line.local
    build: ./command-line
    expose:
      - "8000"
    environment:
      API_HOST: "http://localhost:4000"
      APP_SERVER_PORT: "8000"
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./command-line/src:/srv/app/command-line/src
    depends_on:
      - couchdb
    command:
      npm run start
  couchdb:
    container_name: couchdb
    hostname: couchdb.local
    image: apache/couchdb:${DOCKER_TAG:-latest}
    environment:
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: iniadmin
    volumes: [ '~/data:/opt/couchdb/data' ]
    ports:
    - "5984:5984"