version: "3"
services:
  client:
    container_name: clienttask
    hostname: taskapp.local
    build: ./client
    environment:
      - REACT_APP_PORT="3000"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./client/src:/srv/app/webapp-client/src
      - ./client/public:/srv/app/webapp-client/public
    links:
      - server
    command:
      npm run start
  server:
    container_name: servertask
    hostname: taskapi.local
    build: ./server
    expose:
      - "8000"
    environment:
      API_HOST: "http://localhost:4000"
      APP_SERVER_PORT: "8000"
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./server/src:/srv/app/webapp-server/src
    depends_on:
      - couchdb
    command:
      npm run start
  couchdb:
    container_name: couchdb
    hostname: couchdb.local
    image: apache/couchdb:${DOCKER_TAG:-latest}
    environment:
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: iniadmin
    volumes: [ '~/data:/opt/couchdb/data' ]
    ports:
    - "8080:8080"