FROM mhart/alpine-node:10

RUN mkdir -p /srv/app/webapp-server

WORKDIR /srv/app/webapp-server

COPY package.json /srv/app/webapp-server
COPY package-lock.json /srv/app/webapp-server

RUN yarn install

COPY . /srv/app/webapp-server

CMD ["npm", "run","start"]