version: "1"
services:
  client:
    image: mhart/alpine-node:latest
    restart: always
    port:
      - "3000":"3000"
    working_dir: /client/src/app
    volumes:
      - ./client:/client/src/app
    entrypoint: ["npm","start"]
    links:
      - server
    networks:
      - taskappnetwork
  server:
    image: taskapp-server
      restart: always
      ports:
        - "9000:9000"
      volumes:
        - ./server:/server
        - /api/node_modules
      depends_on:
        - couchdb
      networks:
        taskappnetwork
  couchdb:
    container_name: couchdb
    hostname: couchdb.local
    image: apache/couchdb:${DOCKER_TAG:-latest}
    environment:
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: iniadmin
    volumes: [ '~/data:/opt/couchdb/data' ]
    ports:
    - "5984:5984"